version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g yarn
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      # copy the contents of /build to S3
      - aws s3 sync ./build s3://hrhyv2-front-policy/

      - yarn invalidate
artifacts:
  files:
    - '**/*'
  base-directory: build
